---
- hosts: all 
  become: yes

  tasks:
    # - name: Set authorized key taken from file
    #   authorized_key:
    #     user: root
    #     state: present
    #     key: "{{ lookup('file', 'id_rsa.pub') }}"
    - name: Add HCP signing key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
    - name: Add Docker signing key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add hcp into sources list
      ansible.builtin.apt_repository:
        repo: deb https://apt.releases.hashicorp.com jammy main
        state: present
    - name: Add docker repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable 
        state: present
    - name: ensure apt cache is updated
      action: apt update_cache=yes
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist
    - name: ensure all software is installed
      action: apt name={{item}}
      with_items:
        - wget
        - curl
        - ca-certificates
        - gnupg
        - lsb-release
        - nomad
        - consul
        - zip
        - tar
        - vault
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - software-properties-common
        - apt-transport-https
    - name: add group consul
      group: name='consul'
    - name: add consul user
      user: name='consul' groups="consul"
    - name: Creates config dir
      file:
        path: /etc/consul.d
        state: directory
        owner: consul
        group: consul
        mode: 0755
    - name: Creates certs dir
      file:
        path: /etc/consul.d/certs
        state: directory
        owner: consul
        group: consul
        mode: 0755

    - name: Creates data dir
      file:
        path: /opt/consul
        state: directory
        owner: consul
        group: consul
        mode: 0755
    - name: copy consul agent ca 
      copy:
        src: secrets/consul/consul-agent-ca.pem
        dest: /etc/consul.d/certs/consul-agent-ca.pem
        owner: consul
        group: consul
        mode: 0755
    - name: copy consul client key
      copy:
        src: secrets/consul/consul-agent-ca-key.pem
        dest: /etc/consul.d/certs/consul-agent-ca-key.pem
        owner: consul
        group: consul
        mode: 0755
    - name: copy consul client key
      copy:
        src: consul/resolved.conf
        dest: /etc/systemd/resolved.conf
        mode: 0755
    - name: copy consul service file
      copy:
        src: consul/consul.service
        dest: /etc/systemd/system/consul.service
        mode: 0755
    - name: copy consul exporter service
      copy:
        src: consul/consul-exporter.service
        dest: /etc/systemd/system/consul-exporter.service
        mode: 0755
    - name: copy consul_exporter
      copy:
        src: consul/install-exporter.sh
        dest: /root/install-exporter.sh
        mode: 0755
    - name: Install consul exporter
      ansible.builtin.command: /root/install-exporter.sh
    - name: Download cni plugin
      ansible.builtin.command: curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-amd64-v1.0.0.tgz
    - name: Creates cni dir
      file:
        path: /opt/cni/bin
        state: directory
        owner: root
        group: root
        mode: 0755      
    - name: Install CNI plugin
      ansible.builtin.command: tar -C /opt/cni/bin -xzf cni-plugins.tgz
    - name: setup CNI plugin
      ansible.builtin.command: echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-arptables && echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-ip6tables && echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-iptables

- hosts: clients:grafana:prometheus:loki:tempo
  become: yes
  tasks:
    - name: copy agent config
      template:
        src: consul/client.j2
        dest: /etc/consul.d/consul.hcl
        owner: consul
        group: consul
        mode: 0644
- hosts: clients
  become: yes
  tasks:
    - name: copy agent config
      template:
        src: consul/client.j2
        dest: /etc/consul.d/consul.hcl
        owner: consul
        group: consul
        mode: 0644
    - name: Creates config dir
      file:
        path: /etc/nomad.d
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Creates certs dir
      file:
        path: /etc/nomad.d/certs
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Creates data dir
      file:
        path: /opt/nomad
        state: directory
        owner: root
        group: root
        mode: 0700
    - name: copy nomad ca
      copy:
        src: secrets/nomad/nomad-ca.pem
        dest: /etc/nomad.d/certs/nomad-ca.pem
        owner: root
        group: root
        mode: 0755
    - name: copy client.pem
      copy:
        src: secrets/nomad/client.pem
        dest: /etc/nomad.d/certs/client.pem
        owner: root
        group: root
        mode: 0755
    - name: copy client-key.pem
      copy:
        src: secrets/nomad/client-key.pem
        dest: /etc/nomad.d/certs/client-key.pem
        owner: root
        group: root
        mode: 0755
    - name: copy config
      template:
        src: nomad/client.j2
        dest: /etc/nomad.d/nomad.hcl
        owner: root
        group: root
        mode: 0755
    - name: copy service
      copy:
        src: nomad/nomad-client.service
        dest: /etc/systemd/system/nomad.service
        mode: 0755

- hosts: nomad_servers
  become: yes

  tasks:
    - name: Creates config dir
      file:
        path: /etc/nomad.d
        state: directory
        owner: nomad
        group: nomad
        mode: 0755
    - name: Creates certs dir
      file:
        path: /etc/nomad.d/certs
        state: directory
        owner: nomad
        group: nomad
        mode: 0755

    - name: Creates data dir
      file:
        path: /opt/nomad
        state: directory
        owner: nomad
        group: nomad
        mode: 0755
    - name: copy nomad ca
      copy:
        src: secrets/nomad/nomad-ca.pem
        dest: /etc/nomad.d/certs/nomad-ca.pem
        mode: 0755
    - name: copy server.pem
      copy:
        src: secrets/nomad/server.pem
        dest: /etc/nomad.d/certs/server.pem
        mode: 0755
    - name: copy server-key.pem
      copy:
        src: secrets/nomad/server-key.pem
        dest: /etc/nomad.d/certs/server-key.pem
        mode: 0755
    - name: copy config
      template:
        src: nomad/server.j2
        dest: /etc/nomad.d/nomad.hcl
        mode: 0755
    - name: copy service
      copy:
        src: nomad/nomad-server.service
        dest: /etc/systemd/system/nomad.service
        mode: 0755

- hosts: consul_servers
  become: yes

  tasks:
    - name: copy agent ca 
      copy:
        src: secrets/consul/consul-agent-ca.pem
        dest: /etc/consul.d/certs/consul-agent-ca.pem
        owner: consul
        group: consul
        mode: 0644
    - name: copy server pem
      copy:
        src: secrets/consul/dc1-server-consul-0.pem
        dest: /etc/consul.d/certs/dc1-server-consul-0.pem
        owner: consul
        group: consul
        mode: 0644
    - name: copy server key
      copy:
        src: secrets/consul/dc1-server-consul-0-key.pem
        dest: /etc/consul.d/certs/dc1-server-consul-0-key.pem
        owner: consul
        group: consul
        mode: 0644
    - name: copy server config
      template:
        src: consul/server.j2
        dest: /etc/consul.d/consul.hcl
        owner: consul
        group: consul
        mode: 0644

- hosts: all 
  become: yes
  serial: 1

  tasks:
    - name: start consul service on boot
      ansible.builtin.systemd:
        enabled: yes
        name: consul
    - name: start consul-exporter service on boot
      ansible.builtin.systemd:
        enabled: yes
        name: consul-exporter
    - name: Restart consul service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: consul
    - name: Restart consul-exporter service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: consul-exporter
    - name: Restart resolved service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name:  systemd-resolved
   ### nomad clients and servers   
- hosts: nomad_servers:clients 
  become: yes
  serial: 1  
  tasks:
    - name: start nomad service on boot
      ansible.builtin.systemd:
        enabled: yes
        name: nomad
    - name: Restart nomad service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: nomad