dc_name: hetzner
base_dir: config
org_name: chaordic

cluster_config:
  servers: 3 # 3 or 5
  clients: 2
  vault_servers: 2
  consul_volume_size: 11
  separate_consul_servers: false
  client_volumes:
  - name: "data_vol"
    client: "1"
    path: /opt/nomad_client/data
    size: 20
  # host_volume "mysql" {
  #   path      = "/opt/mysql/data"
  #   read_only = false
  # }

observability_config:
  multi_instance: false # sets all on 1 server if false, 4 separate if true
  tempo_bucket: tempo
  loki_bucket: loki

cloud_provider_config:
  internal_network_interface_name: ens10
  sudo_user: root
  sudo_dir: /root
  provider: hetzner
  provider_settings:
    location: nbg1
    ssh_keys:
    - wille.faler@gmail.com
    server_type: cx21
    resource_names:
      base_server_name: venue
      firewall_name: dev_firewall
      network_name: dev_network
    allowed_ips:
    - 85.4.84.201/32
    - 178.197.225.121/32
